version: "3.5"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-diglette-clicker
    working_dir: /app
    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
      - /app/backend/node_modules
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=Edega2003
      - DB_NAME=clicker

  db:
    image: postgres
    command: postgres -c 'max_connections=200'
    container_name: api-db-diglette-clicker
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Edega2003
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U -d postgres_db"]
      interval: 30s
      timeout: 10s
      retries: 5
    tty: true
    stdin_open: true

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=Edega2003
    ports:
      - "7777:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data:
